CREATE TABLE IF NOT EXISTS BRAND (
    ID    SERIAL PRIMARY KEY,
    NAME  VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRICE (
    ID          SERIAL PRIMARY KEY,
    BRAND_ID    INTEGER NOT NULL REFERENCES BRAND(ID),
    START_DATE  TIMESTAMP NOT NULL,
    END_DATE    TIMESTAMP NOT NULL,
    PRICE_LIST  INTEGER NOT NULL,
    PRODUCT_ID  INTEGER NOT NULL,
    PRIORITY    INTEGER NOT NULL,
    PRICE       NUMERIC(10,2) NOT NULL,
    CURRENCY    CHAR(3) NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_PRICE ON PRICE (BRAND_ID, PRODUCT_ID, START_DATE, END_DATE);
